// Light Mode
export const lightMode = {
  bodyColor: "#fefefe",
  navBarTextColor: "#12372A",
  headingColor: "#00967b",
  introBgColor: "#bbb2a9",
  paraColor: "#12372A",
  buttonBgColor1: "#03C988",
  buttonBgColor2: "#9ADE7B",
  buttonTextColor1: "#12372A",
  buttonTextColor2: "#12372A",
  firstSlantColor: "#03C988",
  secondSlantColor: "#bbb2a9",
  slantTextColor: "#12372A",
  cardsBgColor: "#bbb2a9",
  cardsTitleColor: "#000",
  cardsButtonColor: "black",
  footerBgColor: "#bbb2a9",
  footerTextColor: "#12372A",
  copyRightTextColor: "black",
  githubIconColor: "black",
  surahButtonBgColor: "#bbb2a9",
  surahIdColor: "white",
  surahIdBgColor: "#00967b",
  surahEnglishNameColor: "#001017",
  surahArabicNameColor: "#001017",
  displayQuranIconColor: "grey",
  surahHeadingColor: "#00967b",
  surahVersesColor: "#001017",
  translationColor: "#00967b",
  quranPageBgColor: "#fefefe",
  versesTerminatorColor: "#00967b",

};

// Dark Mode

export const darkMode = {
  bodyColor: "#000",
  navBarTextColor: "#999",
  headingColor: "#FBFBFC",
  paraColor: "#999",
  introBgColor: "#0c0c0c",
  buttonBgColor1: "#1A1A1A",
  buttonBgColor2: "#FF6433",
  buttonTextColor1: "#FBFBFC",
  buttonTextColor2: "#FBFBFC",
  firstSlantColor: "#FF6433",
  secondSlantColor: "#B6BBC4",
  slantTextColor: "#000",
  cardsBgColor: "#0c0c0c",
  cardsTitleColor: "#FBFBFC",
  cardsButtonColor: "#fcfcfc",
  footerBgColor: "#1A1A1A",
  footerTextColor: "#999",
  copyRightTextColor: "#FBFBFC",
  githubIconColor: "#FBFBFC",
  surahButtonBgColor: "#1A1A1A",
  surahIdColor: "white",
  surahIdBgColor: "#FF6433",
  surahEnglishNameColor: "#FBFBFC",
  surahArabicNameColor: "#FBFBFC",
  displayQuranIconColor: "white",
  surahHeadingColor: "#FBFBFC",
  surahVersesColor: "#FBFBFC",
  translationColor: "#999",
  quranPageBgColor: "#000",
  versesTerminatorColor: "#FF6433",
};

// export const themeScheme = {
//   lightMode: {
//     bodyColor: "#F5F7F8",
//     firstSlantColor: "#03C988",
//     headingColor: "#12372A",
//     secondSlantColor: "#EFECEC",
//     footerBgColor: "#EFECEC",
//     introSectionBgColor: "#EFECEC",
//     cardsBgColor: "#EFECEC",
//     textColor: "#12372A",
//     footerTextColor: "#12372A",
//     heroSectionButtonColor: "#03C988",
//     introSectionFirstButtonColor: "#03C988",
//     introSectionSecondButtonColor: "#9ADE7B",
//     cardsButtonColor: "black",
//     footerButtonColor: "success",
//   },

//   darkMode: {
//     bodyColor: "#000",
//     firstSlantColor: "#FF6433",
//     headingColor: "#FBFBFC", // To be used in Copyright Footer Text also
//     secondSlantColor: "#B6BBC4",
//     footerBgColor: "#1A1A1A",
//     introSectionBgColor: "#0c0c0c",
//     cardsBgColor: "#0c0c0c",
//     textColor: "#999",
//     footerTextColor: "#999",
//     heroSectionButtonColor: "#FF6433",
//     introSectionFirstButtonColor: "#1A1A1A",
//     introSectionSecondButtonColor: "#FF6433",
//     cardstitleColor: "#fcfcfc",
//     cardsButtonColor: "#fcfcfc",
//     footerButtonColor: "#999",
//   },
// };
